version: "3"
services:
    datascience-notebook:
        image: jupyter/datascience-notebook:latest
        volumes: 
            - ./:/home/jovyan/work
        ports:
            - 8888:8888
            - 6006:6006
        container_name: tensorboard-sample-container
        environment:
            - JUPYTER_ENABLE_LAB=yes